apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
      maxconn 256

    defaults
      mode tcp
      timeout connect 10s
      timeout client 30s
      timeout server 30s

    frontend redis_front
      bind *:{{ .Values.service.port }}
      default_backend redis_back

    backend redis_back
      server redis {{ .Values.redis.host }}:{{ .Values.redis.port }} check
